### ISSUE TITLE
[rclone] Issue while using webdav

### ISSUE THREAD

**Issue by NISH1001** [NASA-IMPACT/data-transfer-evaluation#1]
My configuration is something like:

```text
[catalogue-source]
type = webdav
url = https://beta.databridge.gael-systems.com/gss-catalogue/Products
vendor = other
user = <username>
pass = <base64 encoded password>
bearer_token = <token>
```

# Method 1

Using configuration

```bash
 rclone -vv lsf --http-no-slash catalogue-source: --config=./rclone.conf  --dump  bodies --webdav-vendor other --webdav-bearer-token "$token" --webd    av-url https://beta.databridge.gael-systems.com/gss-catalogue/Products --dump headers
```

# Method 2
Direct configuration from CLI

```bash
rclone -vv lsf --http-no-slash --http-url "https://beta.databridge.gael-systems.com/gss-catalogue/Products" :http: --webdav-vendor other --dump headers --webdav-bearer-token $token --dump bodies
```

---

With method 1, I am getting `403` forbidden status.
With method 2, authentication is not working

**Comment by NISH1001** [comment]
This is the debug log when hitting the server. The same auth token (or username/password) works through curl:

![image](https://user-images.githubusercontent.com/4786694/156673823-58484439-2efc-4441-bb0c-47afbf754d81.png)

I am using method 1 for this.

**Comment by NISH1001** [comment]
Actually, the authentication is successful, but I am trying to access `/Products` endpoint and getting 403 forbidden

![image](https://user-images.githubusercontent.com/4786694/156675337-2f1a5526-ed4c-4928-bda9-1466bd79f0a7.png)

I am using the following command:
```bash
rclone -vv ls  catalogue-source: --config=./rclone.conf  --webdav-vendor other  --dump headers 
```

The config already has a valid `bearer_token`.

**Comment by NISH1001** [comment]
Also one last thing:

It seems rclone is appending a `trailing` slash.
For instance when I am trying to configure to hit the url `https://beta.databridge.gael-systems.com/gss-catalogue/Products?$format=json`, it auto-adds slash as `https://beta.databridge.gael-systems.com/gss-catalogue/Products?$format=json/` which throws `405 forbidden`

![image](https://user-images.githubusercontent.com/4786694/156678783-786e8921-de99-4371-845b-a1e6f96ee923.png)

I can confirm that authentication works fine. But the problem is whether we can list files directly through rclone or not and the problem persists with the trailing slash when fetching the json response.

**Comment by PatrickPradier** [comment]
Hello,

I think it's not possible to use the catalogue as a WebDAV server.
The only supported HTTP methods are :  GET,  POST,  PUT,  PATCH,  MERGE,  DELETE,  HEAD

So it's not possible to use the PROPFIND method.

**Comment by NISH1001** [comment]
@PatrickPradier I am closing this issue for time being. Thanks for your feedback.
