### ISSUE TITLE
Nifi configuration

### ISSUE THREAD

**Issue by PatrickPradier** [NASA-IMPACT/data-transfer-evaluation#14]
Hello,

In the nifi template (https://github.com/NASA-IMPACT/data-transfer-evaluation/blob/master/evalit/nifi/nifi-s3.xml) you used for the tests, it seems that there are some parameters that are not optimal:
- concurrentlySchedulableTaskCount = 1 -> it means that only one thread is used per processor. So only one download in the FetchS3Object and one upload in the PutS3Object can happen at the same time
- backPressureDataSizeThreshold = 1GB -> it means that the queue between the processors cannot go beyond (soft limit) 1GB. So only 1 or 2 files can be in the queue at the same time.

I'm not sure these are the parameters you used for your benchmarks but that could explain the poor results you experienced with Nifi and the flat line we see in the comparison graph.

**Comment by NISH1001** [comment]
Thanks Patrick for pointing that out. Can you share the xml we can use for optimization? @smarru Can you please help with this?

**Comment by NISH1001** [comment]
I have added `xml_conf` to `NifiAutomation`'s constructor to override xml configuration for nifi. If not present, default xml at `nifi/`directory is used.
