### ISSUE TITLE
Issue connecting to bucket

### ISSUE THREAD

**Issue by PatrickPradier** [NASA-IMPACT/data-transfer-evaluation#19]
Hello,

I'm trying to run the benchmarks on my local machine to test rclone and nifi.
I've installed minio locally and have two buckets accessible on http://localhost:9000 with the default minio credentials.

I can access those buckets on command line with aws s3 cli:
```
patrick@cassandra:~/.aws$ aws s3 --profile minio ls --endpoint-url="http://localhost:9000"
2022-04-13 14:56:40 dst-test
2022-04-13 14:56:33 src-test
```
However I have an error when i launch `controller_tes2.py`:
```
patrick@cassandra:~/workspace/data-transfer-evaluation$ python3 tests/controller_test2.py
automation pkg version: 0.1.1
2022-04-13 15:51:23.570 | INFO     | evalit._base:load_yaml:98 - Loading yaml from tests/config.yaml
2022-04-13 15:51:23.572 | DEBUG    | evalit._base:get_source_file_map:195 - Boto3 version: 1.21.39
Traceback (most recent call last):
  File "tests/controller_test2.py", line 26, in <module>
    filemap = StandardAutomationController.get_source_file_map(dt_config)
  File "/home/patrick/workspace/data-transfer-evaluation/./evalit/_base.py", line 203, in get_source_file_map
    response_contents = s3_client.list_objects_v2(
  File "/home/patrick/.local/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/patrick/.local/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

The content of the config.yaml file is :
``` 
---
source_token: "minioadmin"
source_secret: "minioadmin"
source_s3_endpoint: "http://localhost:9000"
source_s3_bucket: "src-test"
source_s3_region: "eu-west-1"

dest_token: "minioadmin"
dest_secret: "minioadmin"
dest_s3_endpoint: "http://localhost:9000"
dest_s3_bucket: "dst-test"
dest_s3_region: "eu-west-1"
```

I probably do something wrong but I don't know what :thinking:

**Comment by NISH1001** [comment]
This is weird. Can you once try running source and destination on separate ports?

**Comment by PatrickPradier** [comment]
Still the same error.
It's strange because it works with the aws s3 cli, and it works as well in a java program using aws java sdk.

It doesn't work with the scrip controller_test2.py but it works with the controller_test.py script.
However, then it does't work in Nifi (`Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed`)

**Comment by NISH1001** [comment]
I will have a look. It's working on my device and Dimuthu was also able to run it. It's weird. Will debug and get back to you. Thanks for pointing this out.

**Comment by NISH1001** [comment]
> Still the same error. It's strange because it works with the aws s3 cli, and it works as well in a java program using aws java sdk.
> 
> It doesn't work with the scrip controller_test2.py but it works with the controller_test.py script. However, then it does't work in Nifi (`Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed`)

The controller_test2.py has new controller component where we fetch the list of files from source bucket at runtime where I am using `boto3` to get the list. Probably, some configuration mismatch with boto3 is going on. I will take a look.

**Comment by smarru** [comment]
@PatrickPradier do you see anything running on port 9000, may be you can check with something like `netstat -altn | grep 9000`

**Comment by NISH1001** [comment]
Currently, we're using boto3 to list all the files from the source. See:
https://github.com/NASA-IMPACT/data-transfer-evaluation/blob/feature/controller/evalit/_base.py#L197=

The controller_test2.py access this method to get all the files:
https://github.com/NASA-IMPACT/data-transfer-evaluation/blob/feature/controller/tests/controller_test2.py#L26=

Probably, it's a configuration issue with boto3. I am able to replicate the issue on my mac too. I will look into this and resolve it. It should be an unseen configuration issue on how boto3 accesses the buckets. I am taking a  look at it...

**Comment by NISH1001** [comment]
@PatrickPradier for now can you temporarily comment out the line to get file maps on controller_test2.py ? And manually create the dictionary. The dictionary is of the form:

```python
filemap == >{'testfile': {'size': 0.95367431640625}, 'testfile.2': {'size': 0.95367431640625}, 'testfile.3': {'size': 0.95367431640625}, 'testfile.4': {'size': 0.95367431640625}, 'testfile.5': {'size': 0.95367431640625}}
```

Sizes are in gigs.

Just to get things started on your side. I will debug the boto3 issue. The reason I had used boto3 was to automate the file listings at runtime.

**Comment by NISH1001** [comment]
@PatrickPradier I found the issue. Without exporting the minio credentials before spinning up the server, it fails to register the creds to aws CLI (I think, or something like that). So, these records didn't exist.

Solution:
While starting the minio server, please export the credentials too:

```bash
export MINIO_ROOT_USER=<username>
export MINIO_ROOT_PASSWORD=<password>
minio server /tmp/eval-bucket/ --address ":9000
```

This solves the issue. Can you please do this and get back to this thread to confirm.

**Comment by PatrickPradier** [comment]
Yes it seems to solve this issue. However a new error is returned now 
```
botocore.exceptions.ClientError: An error occurred (PermanentRedirect) when calling the ListObjectsV2 operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```
Maybe boto3 wants an endpoint to look like `http://s3.us-east-1.172.20.0.1:9000` and not like `http://172.20.0.1:9000`.

Anyway, with this workaround and the previous one (manually listing the files), it worlks and I will be able to execute the tests :+1:

**Comment by NISH1001** [comment]
The boto3 endpoint works nicely with localhost. What is the boto3 version you're using?
