### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by ub0005** [NASA-IMPACT/data-transfer-evaluation#21]
We have to update the README file with more details on how to set up the evaluation framework

**Apache Nifi**:
1) Update the download URL (the current one lands in 404(not found))
2) Command to stop Nifi server has to be updated

**Airavata MFT**
1) Update the download URL (the current one lands in 404(not found))
2) commands to start/stop has to be updated (replace '_' with '-')

**MINIO**
1) An additional section to be added called "Installation of MINIO"
2) Steps to create the buckets has to be included

**Environmental Variables**
1) Add an additional section to mention the environmental variables to be created

**Test Files**
1) Add a command to create the large files in local
command : dd if=/dev/zero of=/{local_path}/testfile2g bs=1024 count=1000000

**Tests**
1) Add an additional section to mention which python scripts to be executed as part of testing

cc: @freitagb @NISH1001

**Comment by NISH1001** [comment]
cc: #23
