### ISSUE TITLE
Unable to run Automation tests

### ISSUE THREAD

**Issue by ub0005** [NASA-IMPACT/data-transfer-evaluation#22]
After installing the required software when I try to run each automation individually resulting in errors.

I am attaching the error screenshots for each automation for your reference.

**Nifi** doesn't give any error message but we could see the files getting transferred sucessfully.
![Nifi-error](https://user-images.githubusercontent.com/98353980/169572384-640a34e4-da6c-4fa3-8161-8e230ac3d4bc.jpg)
**Rclone**
![RClone](https://user-images.githubusercontent.com/98353980/169572398-ff19148e-be69-4df1-9e01-5bd4203792a6.jpg)
**MFT**
![mft-error](https://user-images.githubusercontent.com/98353980/169572431-fc6b128e-5426-45ad-b7f9-5e24ea7e67e8.jpg)

cc: @freitagb @NISH1001

**Comment by NISH1001** [comment]
Related: https://github.com/NASA-IMPACT/data-transfer-evaluation/issues/24
This might be the problem with:
- incompatibility with minio new release ([see](https://github.com/NASA-IMPACT/data-transfer-evaluation/issues/23#issuecomment-1225912916))
- Or mft issue ([see](https://github.com/NASA-IMPACT/data-transfer-evaluation/issues/24))
