### ISSUE TITLE
Unable to run mft in mac

### ISSUE THREAD

**Issue by NISH1001** [NASA-IMPACT/data-transfer-evaluation#24]
cc: https://github.com/NASA-IMPACT/data-transfer-evaluation/issues/23

While `RcloneAutomation` and `NifiAutomation` works fine, I am unable to run `MftAutomation` inside `tests/controller_test2.py` on my mac. (On my linux machine, everything works fine though)

---

![image](https://user-images.githubusercontent.com/4786694/186471843-472357dd-119f-4834-8efc-9f6d23e0aeb6.png)

This happens during the step of fetching storage ids inside the mft automation component. As a result, `source_storage_id` and `dest_storage_id` are empty. I feel this is due to the incompatibility in jdk version? I am using [this release](https://github.com/apache/airavata-mft/releases/tag/0.1-pre-release) of mft that works with the current codebase in this repo.

It seems I am unable to communicate with mft server (although it's already running)

---

cc: @ub0005 @DImuthuUpe

**Comment by xhagrg** [comment]
is this not dockerized? can the tests not be run in the docker container?

**Comment by NISH1001** [comment]
We could try. I was also thinkign the same. But for initial release, it's bare minimum with custom scripts. I am gonna hand it to @ub0005  for now. Maybe we could do in next release after initial?
