### ISSUE TITLE
[Enhancement] Repo cleanup

### ISSUE THREAD

**Issue by NISH1001** [NASA-IMPACT/data-transfer-evaluation#8]
@smarru 

We need to clean up the repo. At this point, our main framework resides inside `evaluation/` directory. And there are other dummies (not sure if they are needed). As a result the repo is "polluted".

We have:
- nifi inside `nifi/`
- minio examples at `minio-example`

---

Can you please help me if we need those two directories? Are they some sort of configuration? Or else we can move them inside the `data/` directory for time being.

**Comment by NISH1001** [comment]
Also, I want to:
- make the main evaluation directory a full-fledged python package. (say, something like `evalit`). This will allow the package to be `pip`-installable.
- move requirements and add setup.py to main repo base directory
- add `tests/` directory to move the tests controller to the tests as anyone can use the test as per their needs.

The final package tentative would look like

```python
from evalit import NifiAutomation, RcloneAutomation
from evalit import Controller

controller = Controller(RcloneAutomation(...))
controller.run_transfer(...)
controller.analyze_transfer(...)
```

**Comment by NISH1001** [comment]
Also, I will create another issue all relating to improving our core (with optimization/improvements) and design decisions where we can brainstorm.

**Comment by smarru** [comment]
+1 for remove everything legacy and starting over with just evaluation code

**Comment by smarru** [comment]
Also, we need to have clean instructions for running the evaluation of local laptop, configuring network and other details such as on emulab and instantiating VM's and running and so forth

**Comment by NISH1001** [comment]
Ya. Agree. I was able to run minio test s3 buckets on my local. So one instructions could be running end-to-end locally (removing network caveats). Other could be emulab. But I think both will 50% overlap on creating test buckets, etc.

**Comment by NISH1001** [comment]
I will move `nifi` and `minio-example` directories to a more grounded legacy directory called `sandbox` then.
